name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, armhf]
        include:
          - arch: amd64
            triplet: x86-64-linux-gnu
            compiler: g++
          - arch: arm64
            triplet: aarch64-linux-gnu
            compiler: aarch64-linux-gnu-g++
          - arch: armhf
            triplet: arm-linux-gnueabihf
            compiler: arm-linux-gnueabihf-g++

    steps:
      - uses: actions/checkout@v4

      - name: Install compiler & deps
        run: |
          sudo apt-get update
          sudo apt-get purge needrestart
          sudo apt-get install -y uuid-dev g++-${{ matrix.triplet }}

      - name: Build
        run: make

      - name: Upload binary files
        uses: actions/upload-artifact@v4
        with:
          name: phira-mp-server-linux-${{ matrix.arch }}
          path: ./phira-mp-server
